### ISSUE TITLE
Set up a Database for the Orders

### ISSUE THREAD

**Issue by Muqinn** [CSCI-GA-2820-FA23-003/orders#14]
**As an** Administrator
**I need** set up a space to store order data
**So that** we can efficiently manage and retrieve order-related information

### Details and Assumptions

- Order data includes information about products, quantities, prices, customer details, and order timestamps
- An unique order IDs will be generated for each order
- Orders may have various statuses, such as "pending," "processing," "shipped," "delivered," or "cancelled."
- Administrator can access and edit the database to support future enhancements such as order tracking and analytics
- Access to the database should be restricted to authorized personnel only

### Acceptance Criteria
```
Given we have a database accessible through order ID
When I perform a query through order ID
Then I receive the query result
```

**Comment by darkness1418** [comment]
Since we decided to use the PostgreSQL which has already been added, there's not much to do in this step. Database setting up task falls on how we define our model.
